name: Pre-merge check new

on:
  pull_request:

jobs:
  job_1:
    name: Pre merge check
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: npm run build

      - name: Run eslint
        run: npm run lint

      - name: Run unit tests
        run: npm run test
